### ISSUE TITLE
Style guide URLs are incorrect

### ISSUE THREAD

**Issue by cjschroder** [SUSEdoc/susedoc.github.io#29] opened 2021-10-04 21:20 UTC
The Style Guide URLs on susedoc.github.io return 404s. They look correct, according to what I see in the configurations, for example:

`https://susedoc.github.io/doc-styleguide/main/html/docu_styleguide/`

However, this results in a 404. See https://susedoc.github.io/doc-styleguide/main/ for the URLs that work correctly. I have started debugging this; anyone who wishes to join the fun is welcome.

**Comment by sknorr** [comment] 2021-10-05 11:22
This is a dupe of #27 -> closing.

**Closed by sknorr** 2021-10-05 11:22 UTC
